appFromExternalRepo:
  enabled: false
command:
  - dotnet
args:
  - "/App/MinimalWeb.dll"
image:
  repository: rsciriano/k8s-minimal-web
  tag: dnz-demo5
  #pullPolicy: Always

ingress:
  enabled: true
  pathType: Prefix
  hostname: kubernetes.docker.internal
  path: /rob-demo
  ingressClassName: nginx

extraEnvVars:
  - name: Logging__LogLevel__Default
    value: Information
  - name: Logging__ApplicationInsights__LogLevel__Default
    value: Information
  - name: AppVersion
    value: dnz-demo5-probes2
  - name: RequestTimeoutMs
    value: "3000"
extraEnvVarsSecret: rob-demo-secrets

resources:
  requests:
    cpu: 80m
    memory: 250Mi
  limits:
    cpu: 100m
    memory: 250Mi

autoscaling:
  enabled: true     # Enable autoscaling for ASP.NET Core	(false)
  minReplicas: 2    # Minimum number of ASP.NET Core replicas	(1)
  maxReplicas: 30   # Maximum number of ASP.NET Core replicas	(11)
  targetCPU: 70	    # Target CPU utilization percentage	("")
  # Target Memory utilization percentage	()"")
  #targetMemory: 90
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 10
      policies:
      - type: Percent
        value: 25
        periodSeconds: 15
      - type: Pods
        value: 4
        periodSeconds: 15
      selectPolicy: Max
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent
        value: 25
        periodSeconds: 15
      - type: Pods
        value: 4
        periodSeconds: 15
      selectPolicy: Max

# https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/deployment-v1/#DeploymentSpec
updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0

startupProbe:
  enabled: true

customStartupProbe:
  httpGet:
    path: /probes/startup
    port: 8080
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 10
  successThreshold: 1
customReadinessProbe:
  httpGet:
    path: /probes/readiness
    port: 8080
  initialDelaySeconds: 10
  periodSeconds: 5
  timeoutSeconds: 1
  failureThreshold: 6
  successThreshold: 1
customLivenessProbe:
  httpGet:
    path: /probes/liveness
    port: 8080
  initialDelaySeconds: 10
  periodSeconds: 5
  timeoutSeconds: 6
  failureThreshold: 12
  successThreshold: 1
