resources:
  requests:
    cpu: 80m
    memory: 100Mi
  limits:
    cpu: 100m
    memory: 100Mi

autoscaling:
  enabled: true     # Enable autoscaling for ASP.NET Core	(false)
  minReplicas: 2    # Minimum number of ASP.NET Core replicas	(1)
  maxReplicas: 8    # Maximum number of ASP.NET Core replicas	(11)
  targetCPU: 70	    # Target CPU utilization percentage	("")
  # Target Memory utilization percentage	()"")
  #targetMemory: 90  

startupProbe:
  enabled: true

customStartupProbe:
  httpGet:
    path: /probes/startup
    port: 8080
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 10
  successThreshold: 1
customReadinessProbe:
  httpGet:
    path: /probes/readiness
    port: 8080
  initialDelaySeconds: 10
  periodSeconds: 5
  timeoutSeconds: 1
  failureThreshold: 6
  successThreshold: 1
customLivenessProbe:
  httpGet:
    path: /probes/liveness
    port: 8080
  initialDelaySeconds: 10
  periodSeconds: 5
  timeoutSeconds: 6
  failureThreshold: 12
  successThreshold: 1

# https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/deployment-v1/#DeploymentSpec
updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 10%
    maxUnavailable: 0
