appFromExternalRepo:
  enabled: false
command:
  - dotnet
args:
  - "/App/MinimalWeb.dll"
image:
  repository: rsciriano/k8s-minimal-web
  tag: dnz-demo1
  #pullPolicy: Always

ingress:
  enabled: true
  pathType: Prefix
  hostname: kubernetes.docker.internal
  path: /rob-demo
  ingressClassName: nginx

extraEnvVars:
  - name: Logging__LogLevel__Default
    value: Information
  - name: Logging__Application__Insights__LogLevel__Default
    value: Information
  - name: AppVersion
    value: dnz-demo1
extraEnvVarsSecret: rob-demo-secrets
