resources:
  requests:
    cpu: 80m
    memory: 100Mi
  limits:
    cpu: 100m
    memory: 100Mi

#replicaCount: 4
autoscaling:
  enabled: true     # Enable autoscaling for ASP.NET Core	(false)
  minReplicas: 2    # Minimum number of ASP.NET Core replicas	(1)
  maxReplicas: 8    # Maximum number of ASP.NET Core replicas	(11)
  targetCPU: 70	    # Target CPU utilization percentage	("")
  # Target Memory utilization percentage	()"")
  #targetMemory: 90
  #behavior:
  #  scaleDown:


# [Append to a list in values.yaml? · Issue #6569 · helm/helm](https://github.com/helm/helm/issues/6569)
#extraEnvVars:
#  - name: DemoName
#    value: Resources4
